#!/usr/bin/env python3
"""Build source-faithful warehouse metadata from harvested primary production data.

This script intentionally preserves *all* variables found in parsed source tables.
It does not replace the coarticulation schema; it creates an analysis-agnostic layer
from which coarticulation and other phonetic views can be derived.

Expected input is an `audit_output/` directory generated by audit_open_data.py.
Publicly downloadable files are NOT assumed redistributable: source tables whose
license has not been explicitly verified are represented by immutable source
references/checksums + complete variable dictionaries, not mirrored into GitHub.
PAVOQUE is handled separately because its repository license is explicit.
"""
from __future__ import annotations

import argparse, csv, hashlib, re
from pathlib import Path
import pandas as pd

SOURCE_META = {
    "cohn_zellou_2023_clear_speech": dict(
        provenance="AUTO_THEN_ALL_CORRECTED",
        manual_scope="MFA initial alignment; every analyzed target-vowel boundary reviewed and hand-corrected by trained RAs",
        redistribution="REFERENCE_ONLY_LICENSE_NOT_CONFIRMED"),
    "swehvd_2023_2024": dict(
        provenance="AUTO_THEN_ALL_CORRECTED",
        manual_scope="SweFA estimates; relevant vowel boundaries manually corrected by first author",
        redistribution="REFERENCE_ONLY_LICENSE_NOT_CONFIRMED"),
    "mitra_dutta_2023_bengali_english": dict(
        provenance="MANUAL_FROM_SCRATCH",
        manual_scope="recordings manually segmented and annotated in Praat",
        redistribution="REFERENCE_ONLY_LICENSE_NOT_CONFIRMED"),
    "chaturvedi_shaw_2025_vowel_errors": dict(
        provenance="AUTO_THEN_ALL_CORRECTED",
        manual_scope="MFA segmentations manually corrected; Praat formant estimates manually checked/corrected",
        redistribution="REFERENCE_ONLY_LICENSE_NOT_CONFIRMED"),
    "cox_dideriksen_kerenportnoy_2023_danish_ids": dict(
        provenance="MANUAL_FROM_SCRATCH",
        manual_scope="all analyzed vowel onsets/offsets manually segmented in Praat",
        redistribution="REFERENCE_ONLY_LICENSE_NOT_CONFIRMED"),
    "pavoque": dict(
        provenance="AUTO_THEN_ALL_CORRECTED",
        manual_scope="phone labels/segment boundaries manually checked and corrected where needed",
        redistribution="REDISTRIBUTABLE_CC_BY_NC_SA_4_0"),
}

DOMAIN_PATTERNS = [
    ("speaker_id", r"speaker|subject|participant|talker|^p_id$"),
    ("demographic", r"age|gender|sex|education|childage|childgender|first_child"),
    ("language_context", r"language|\bl1\b|\bl2\b|context"),
    ("recording_trial", r"filename|file_name|utterance|trial|token|repetition|counter"),
    ("lexical_stimulus", r"word|sentence|prompt|targetword|target$|pred$"),
    ("segment_label", r"vowel|phone|segment|structure|preced|following|previous_sound|next_sound"),
    ("formant", r"(^|_)f[1-5]($|_)|formant|vowelspace|\bvsa\b"),
    ("f0_pitch", r"(^|_)f0($|_)|meanf0|maxf0|minf0|rangef0|q[0-9]+f0|pitch"),
    ("nasality", r"a1p0|nasal|nasalance"),
    ("amplitude_intensity", r"intensity|rms|amplitude"),
    ("voice_quality", r"cpp|hnr|h1|h2|jitter|shimmer|creak|breath"),
    ("temporal", r"duration|start|end|time|rate|pause|asd|speakingtot|voicedcount"),
    ("prosodic", r"stress|focused|quantity|speechstyle|style"),
    ("condition", r"task|style|speechstyle|condition|group|error|prod_group|coart_type"),
    ("derived_model", r"estimate|est.error|q2.5|q97.5|seed|parameter|z$|_z$|lratio|cumulative_probability|speakercenter|standardized|lmn|midpoint"),
]

def sha256(path: Path) -> str:
    h=hashlib.sha256()
    with path.open('rb') as fh:
        for b in iter(lambda: fh.read(1024*1024), b''): h.update(b)
    return h.hexdigest()

def domain(name: str) -> str:
    x=name.lower()
    for d,p in DOMAIN_PATTERNS:
        if re.search(p,x): return d
    return "source_specific"

def units(name: str) -> str:
    x=name.lower()
    if re.search(r"(^|_)f[1-5]($|_)|f0|formant|pitch",x): return "Hz_or_source_scale"
    if "duration" in x: return "source_units; inspect source documentation"
    if re.search(r"start|end|time",x): return "source_time_units"
    if "rate" in x: return "source_rate_units"
    return ""

def time_reference(name: str) -> str:
    m=re.search(r"_time([2-6])$", name, re.I)
    if m:
        centers={"2":"21.45%","3":"35.75%","4":"50.05%","5":"64.35%","6":"78.65%"}
        return centers[m.group(1)] + " normalized-vowel window center (Cohn-Zellou)"
    m=re.search(r"_(5|15|25|35|45)$", name)
    if m and re.search(r"F[12]",name,re.I): return m.group(1)+"% normalized vowel time"
    return ""

def read_table(path: Path):
    try:
        return pd.read_csv(path, low_memory=False)
    except Exception:
        try: return pd.read_csv(path, sep='\t', low_memory=False)
        except Exception: return None

def sample_levels(s: pd.Series) -> str:
    vals=s.dropna().astype(str).unique()[:12]
    return " | ".join(vals)[:1000]

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--audit-dir',type=Path,default=Path('audit_output'))
    ap.add_argument('--outdir',type=Path,default=Path('manual_phonetic_production/data/warehouse'))
    args=ap.parse_args(); args.outdir.mkdir(parents=True,exist_ok=True)
    (args.outdir/'source_faithful').mkdir(exist_ok=True)

    manifest=[]; tables=[]; vars=[]
    mf=args.audit_dir/'osf_manifest.csv'
    if mf.exists():
        m=pd.read_csv(mf)
        for _,r in m.iterrows():
            manifest.append(dict(source_id=r.get('source_id',''),provider=r.get('provider',''),path=r.get('path',''),size_bytes=r.get('size',''),modified=r.get('modified',''),source_uri=r.get('download',''),sha256='',redistribution_policy=SOURCE_META.get(r.get('source_id',''),{}).get('redistribution','REFERENCE_ONLY')))

    table_dir=args.audit_dir/'tables'
    if table_dir.exists():
        for p in sorted(table_dir.iterdir()):
            if not p.is_file(): continue
            sid=p.name.split('__',1)[0]
            df=read_table(p)
            if df is None: continue
            tables.append(dict(source_id=sid,source_file=p.name,n_rows=len(df),n_columns=len(df.columns),sha256=sha256(p),redistribution_policy=SOURCE_META.get(sid,{}).get('redistribution','REFERENCE_ONLY')))
            meta=SOURCE_META.get(sid,{})
            for c in df.columns:
                s=df[c]
                vars.append(dict(source_id=sid,source_file=p.name,original_variable=str(c),standardized_variable='',variable_domain=domain(str(c)),description="Source variable retained verbatim; semantic mapping remains conservative unless explicitly documented",units=units(str(c)),datatype=str(s.dtype),coding_or_sample_levels=sample_levels(s),missing_fraction=round(float(s.isna().mean()),6),missing_value_conventions="NA/blank as parsed; source-specific sentinels require source documentation",measurement_annotation_method=meta.get('manual_scope',''),time_reference_or_window=time_reference(str(c)),anatomical_or_acoustic_target=domain(str(c)),annotation_provenance=meta.get('provenance',''),notes="Original values are not overwritten by harmonization"))

    # Add PAVOQUE segment observation schema even if the large derived file is kept outside GitHub.
    p=args.audit_dir/'pavoque_segments.csv'
    if p.exists():
        df=pd.read_csv(p,low_memory=False); sid='pavoque'; meta=SOURCE_META[sid]
        tables.append(dict(source_id=sid,source_file='pavoque_segments.csv',n_rows=len(df),n_columns=len(df.columns),sha256=sha256(p),redistribution_policy=meta['redistribution']))
        for c in df.columns:
            s=df[c]; vars.append(dict(source_id=sid,source_file='pavoque_segments.csv',original_variable=str(c),standardized_variable='',variable_domain=domain(str(c)),description="Parsed from licensed PAVOQUE YAML phone segmentation",units=units(str(c)),datatype=str(s.dtype),coding_or_sample_levels=sample_levels(s),missing_fraction=round(float(s.isna().mean()),6),missing_value_conventions="NA/blank",measurement_annotation_method=meta['manual_scope'],time_reference_or_window=time_reference(str(c)),anatomical_or_acoustic_target=domain(str(c)),annotation_provenance=meta['provenance'],notes="Source labels retained as SAMPA; do not infer IPA where mapping is undocumented"))

    pd.DataFrame(manifest).drop_duplicates().to_csv(args.outdir/'file_manifest.csv',index=False)
    pd.DataFrame(tables).drop_duplicates().to_csv(args.outdir/'table_inventory.csv',index=False)
    pd.DataFrame(vars).drop_duplicates().to_csv(args.outdir/'variable_dictionary.csv',index=False)
    status=[]
    td=pd.DataFrame(tables); vd=pd.DataFrame(vars); md=pd.DataFrame(manifest)
    for sid in sorted(set(md.source_id if len(md) else []).union(td.source_id if len(td) else [])):
        status.append(dict(source_id=sid,files_discovered=int((md.source_id==sid).sum()) if len(md) else 0,tables_parsed=int((td.source_id==sid).sum()) if len(td) else 0,rows_parsed=int(td.loc[td.source_id==sid,'n_rows'].sum()) if len(td) else 0,variables_discovered=int((vd.source_id==sid).sum()) if len(vd) else 0,redistribution_policy=SOURCE_META.get(sid,{}).get('redistribution','REFERENCE_ONLY'),status='PARSED_REFERENCE_LAYER' if int((td.source_id==sid).sum()) else 'MANIFEST_ONLY',pending='Continue source-faithful ingest; retain all variables; verify redistribution license before mirroring observations'))
    pd.DataFrame(status).to_csv(args.outdir/'ingestion_status.csv',index=False)
    print(f"warehouse: {len(manifest)} files; {len(tables)} parsed tables; {sum(x['n_rows'] for x in tables)} rows; {len(vars)} variable records")

if __name__=='__main__': main()
